const copy = {
  en: {
    navWork:'Work',navProfile:'Profile',navContact:'Contact',hireMe:'Hire me',availability:'Available for remote opportunities',heroLine1:'Web experiences',heroLine2:'built with purpose.',heroLead:'I combine front-end development, data-driven interfaces and more than four years of real-world experience in operations, customer support and process organization.',viewWork:'View selected work',resumeEn:'Resume · EN',resumePt:'CV · PT-BR',roleLabel:'FOCUS',roleValue:'Front-end · Digital Operations',basedLabel:'BASED IN',stackLabel:'CORE STACK',selectedWork:'Projects designed to solve real problems.',selectedIntro:'Interfaces, data products and digital experiences developed from concept to implementation.',dcType:'DATA PLATFORM · WEB APPLICATION',dcDesc:'An independent music chart platform with weekly rankings, historical archives, artist and album pages, movement data, responsive interfaces and a growing data layer.',liveSite:'Live site ↗',vitaDesc:'A modern, responsive institutional redesign focused on hierarchy, storytelling, accessibility, strong CTAs and a 360° campus experience.',liveDemo:'Live demo ↗',brDesc:'A historical music-chart interface built with React and TypeScript, combining structured datasets, routing and chart-oriented data visualization.',awardsDesc:'An interactive awards archive with edition navigation, category browsing, search, winner states and responsive presentation.',profileTitle:'Development with operational context.',profileStory:'I am building my career in technology on top of a strong professional foundation in administration, legal support, customer service, CRM, financial routines and process automation.',profileStory2:'That combination helps me think beyond the interface: I care about the person using the product, the workflow behind it and whether the solution actually makes work easier.',cap1:'Responsive front-end development',cap2:'Data-heavy interfaces & dashboards',cap3:'Digital operations & process organization',cap4:'Customer support & CRM workflows',cap5:'Document design & editorial layout',expYears:'4+ years',expYearsSub:'professional experience',modernStack:'modern front-end stack',opsTools:'operations toolkit',languages:'native / intermediate / intermediate',contactTitle:'Let’s build something useful.',contactText:'Open to remote roles, freelance projects and collaborations in front-end development, digital operations, support and data-oriented products.'
  },
  pt: {
    navWork:'Projetos',navProfile:'Perfil',navContact:'Contato',hireMe:'Fale comigo',availability:'Disponível para oportunidades remotas',heroLine1:'Experiências digitais',heroLine2:'criadas com propósito.',heroLead:'Combino desenvolvimento front-end, interfaces orientadas a dados e mais de quatro anos de experiência real em operações, atendimento e organização de processos.',viewWork:'Ver projetos selecionados',resumeEn:'Currículo · EN',resumePt:'Currículo · PT-BR',roleLabel:'FOCO',roleValue:'Front-end · Operações Digitais',basedLabel:'LOCALIZAÇÃO',stackLabel:'STACK PRINCIPAL',selectedWork:'Projetos pensados para resolver problemas reais.',selectedIntro:'Interfaces, produtos de dados e experiências digitais desenvolvidas do conceito à implementação.',dcType:'PLATAFORMA DE DADOS · APLICAÇÃO WEB',dcDesc:'Plataforma independente de charts musicais com rankings semanais, arquivo histórico, páginas de artistas e álbuns, movimentação de posições, interface responsiva e camada crescente de dados.',liveSite:'Site ao vivo ↗',vitaDesc:'Redesign institucional moderno e responsivo, focado em hierarquia, narrativa, acessibilidade, CTAs claros e experiência de visita 360°.',liveDemo:'Demo ao vivo ↗',brDesc:'Interface histórica de charts construída com React e TypeScript, combinando datasets estruturados, rotas e visualizações orientadas a rankings.',awardsDesc:'Arquivo interativo de premiações com navegação por edições, categorias, busca, destaque de vencedores e apresentação responsiva.',profileTitle:'Desenvolvimento com visão operacional.',profileStory:'Estou construindo minha carreira em tecnologia sobre uma base profissional sólida em administração, suporte jurídico, atendimento, CRM, rotinas financeiras e automação de processos.',profileStory2:'Essa combinação me ajuda a pensar além da interface: considero quem usa o produto, o fluxo de trabalho por trás dele e se a solução realmente facilita a operação.',cap1:'Desenvolvimento front-end responsivo',cap2:'Interfaces e dashboards com muitos dados',cap3:'Operações digitais e organização de processos',cap4:'Atendimento e fluxos de CRM',cap5:'Design de documentos e diagramação editorial',expYears:'4+ anos',expYearsSub:'de experiência profissional',modernStack:'stack front-end moderna',opsTools:'ferramentas de operação',languages:'nativo / intermediário / intermediário',contactTitle:'Vamos construir algo útil.',contactText:'Aberto a vagas remotas, projetos freelance e colaborações em front-end, operações digitais, suporte e produtos orientados a dados.'
  }
};
let lang='en';
const btn=document.getElementById('langToggle');
function apply(){document.documentElement.lang=lang==='en'?'en':'pt-BR';document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(copy[lang][key])el.textContent=copy[lang][key]});btn.textContent=lang==='en'?'PT':'EN'}
btn.addEventListener('click',()=>{lang=lang==='en'?'pt':'en';apply()});apply();
